SabakiHQ/Sabaki

README.md, main.js, modules/sprint.js, package.json, view/index.js, view/index.view.js
Get rid of Mootools and use Sprint instead. This is the spiritual successor to #47.
=> Replace Mootools with Sprint

view/index.view.js
When there's a huge amount of games inside a SGF collection, it takes a long time to open the 'Manage Games...' dialog, mainly because Sabaki tries to generate preview images for all of the games at once. To alleviate this, we only generate preview images for the items that are visible, and update once we start scrolling or resizing the window.
Closes #125
=> SVG on the fly

.travis.yml, CHANGELOG.md, browser/index.js, browser/ipc.js, browser/view.js, package.json
This PR puts all functions in `index.js` in a global object named `sabaki`. This prevents Sabaki from polluting the global namespace and also sets the foundation of a Sabaki API (see #112). Since `index.js` and `view.js` depend on each other and `browserify` has trouble with circular dependencies, putting the functions into a global object may solve the problem.
Testing:
=> Global `sabaki` object

modules/ngf.js
This fixes handicap placement for NGF when the board is not 19x19. (I
think GIB is always 19x19).
=> Use boardsize when creating Board for .getHandicapPlacement()

modules/board.js, test/boardTests.js
This allows stones to be overwritten.
I trust that makeMove() is never called as a legality checker, i.e. you never call it just to check the result isn't null. Currently, that seems to be true.
Closes #182.
=> Allow stone overwrites

modules/sgf.js, test/sgfTests.js
Note that I had to change the signature of exports.parseTokens(), its
third argument is now an encoding (possibly null) instead of
ignoreEncoding.
Closes #188
=> Allow detection of charset if CA not present

modules/gtp/index.js
=> Fix how parseCommand sends arguments to Command class

components/App.js, components/drawers/InfoDrawer.js
When both changing the komi value of an opened sgf file and attaching a gtp engine _during a single visit of the info drawer_, the old komi value remaining in inferredState is used in syncEngines() after the button 'OK' is clicked. This causes the old komi value being sent to gtp in the initialization of the engine. I try to fix this bug with this commit. Not sure my fix is proper though. Please check, thanks.
=> trying to fix incorrect komi value sent to gtp

src/components/GameGraph.js, src/setting.js
Use darkened blue/purple color to inactive nodes that have comment/bookmark on it. This could help in showing where all the comments are, when reading others' game reviews.
=> change color of special inactive nodes

src/components/drawers/PreferencesDrawer.js, src/main.js, src/setting.js
**Goal:**
To let users turn hardware acceleration on/off. By default, it's turned on, but turning it off may help people with slower PCs, and it also lets capturing software (e.g. OBS) to capture the Sabaki window.
**Description:**
This PR adds an `app.enable_hardware_acceleration` key to the `setting`, which controls whether the app will be launched with hardware acceleration enabled. To control this setting, a checkbox was added to the PreferencesDrawer. The default state is left unchanged.
=> Add an option to toggle the hardware acceleration

src/components/drawers/InfoDrawer.js, src/components/drawers/PreferencesDrawer.js, src/setting.js
This adds a setting in the config file so users can see the result of a game without having to click.
=> Add app.always_show_result option

src/components/App.js, src/modules/rotation.js
(For the rotation functions.)
When boardsize is > 26, we can't simply use ASCII values for min() and max() because SGF uses lowercase values to mean lower numbers, but ASCII has them as higher numbers.
=> Make things more robust when size > 26

src/menu.js
Trivial thing, but it was bugging me.
=> Correct "Respository" misspelling

docs/guides/theme-directory.md
Updated theme directory with additional user theme based on the BattsGo twitch stream. Although it's not meant to be a fully practical theme, it showcases what can be done with themes in general and is a good addition to diversify the current themes for v0.40.0
=> Updated theme directory with additional user created theme.

src/components/App.js
When toggling right or left sidebars, the board doesn't get resized & redrawn to fit the window.
This fixes that.
=> Resize gameboard when toggling show sidebars

src/components/WinrateGraph.js, src/components/drawers/PreferencesDrawer.js, src/setting.js
I don't know if you'll like this, but this adds an option to invert the winrate graph so that the data line itself tracks Black's winrate, which I think is more intuitive, Black being player 1 and all.
I didn't fully understand the render function so hacked at it as best I could. If you decide to accept it, I'd recommend checking my changes make sense...
Also, there's the minor issue that the change in the preferences won't take effect until the graph is redrawn. In fact, one could argue it doesn't need a preferences item at all, with the `settings.json` item being sufficient.
=> Winrate graph invert option

src/components/ContentDisplay.js, src/components/Goban.js, src/components/drawers/PreferencesDrawer.js, src/setting.js
This enables to switch on/off the variasions display started by mouse over.
It corresponds to the last comment in #649 .
=> Add the option to switch on/off the display of variations

package.json, src/main.js, src/setting.js
#586 
This breaks package, at least portable will not work.
It needs `node_modules/{electron-store,conf,ajv,debounce-fn,mimic-fn,dot-prop,is-obj,env-paths,json-schema-typed,make-dir,semver,onetime,pkg-up,find-up,locate-path,p-locate,p-limit,path-exists,write-file-atomic,imurmurhash,is-typedarray,signal-exit,typedarray-to-buffer,type-fest,p-try,uri-js,……}/**/*",`
I'm not sure how much the `……` should be.
works: `"!node_modules"` => `"node_modules"`
=> Preserve window maximized state

src/components/App.js
Do not support sub-folder engine path:
```
events.js:187 Uncaught Error: spawn ./0/Leela0110GTP_OpenCL.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
at onErrorNT (internal/child_process.js:456)
at processTicksAndRejections (internal/process/task_queues.js:80)
errnoException @ internal/errors.js:474
ChildProcess._handle.onexit @ internal/child_process.js:264
onErrorNT @ internal/child_process.js:456
processTicksAndRejections @ internal/process/task_queues.js:80
```
=> Change working directory to portable path.

src/modules/enginesyncer.js
=> Call spawn with absolute path if the file exists, or relative path if it doesn't

src/components/App.js
Running the engine over SSH may leave the engine's processes on the remote computer. This PR prevents it.
Also, if await sabaki.detachEngines() is done before sabaki.window.close(), it may take a long time to close the window, so await is at the end.
=> Detach all engines when the window closed

package.json
Add build for arm64, so we can run Sabaki on Jetson Devices.
Tested on Jetson Xavier NX (JetPack 4.4).
=> Add build for arm64

src/menu.js
This adds a 'Quit' option under the 'File' menu. (#741)
=> Added 'Quit' option under 'File'

src/components/MarkdownContentDisplay.js
Link class was external, and the contentDisplay checked for "comment-external" class to open the link outside the window
=> Link class was incorrect. Correcting issue #748

src/components/App.js
I also had issue #719 on my Windows 10 PC. `window.setContentSize` expects integer arguments but `widthDiff` is not (always) a whole number. I have verified that this fix works by building and running Sabaki on my PC.
I love Sabaki! Thanks a lot for all your hard work!
=> Fix crash on “View Comments” (#719)

.github/workflows/ci.yml, .github/workflows/create-release.yml, package.json, src/components/App.js, src/components/BusyScreen.js, src/components/ContentDisplay.js, src/components/Goban.js, src/components/LeftSidebar.js, src/components/MainMenu.js, src/components/Sidebar.js, src/components/ThemeManager.js, src/components/bars/AutoplayBar.js, src/components/drawers/CleanMarkupDrawer.js, src/components/drawers/GameChooserDrawer.js, src/components/drawers/InfoDrawer.js, src/components/drawers/PreferencesDrawer.js, src/components/drawers/ScoreDrawer.js, src/components/sidebars/CommentBox.js, src/components/sidebars/GameGraph.js, src/components/sidebars/Slider.js, src/components/sidebars/WinrateGraph.js, src/i18n.js, src/main.js, src/menu.js, src/modules/dialog.js, src/modules/enginesyncer.js, src/modules/gtplogger.js, src/modules/helper.js, src/modules/sabaki.js, src/modules/sound.js
- Bump to electron 9.4.4 and fix incompatibility
- Bump to electron 10.4.7
- Bump electron to v11.4.8
- Update GA workflows to use latest Node LTS
- Replace deprecated remote module with @electron/remote
- Jump to Electron 12.0.0
- Upgrade to final latest electron v13.1.4.
=> Upgrade to latest Electron, thus adding M1 Mac Support

src/components/sidebars/CommentBox.js, style/index.css
When the comment box is hidden and edit mode is being turned on, the layout and therefore the mouse event handling on the game graph gets messed up (offset by some amount).
I fixed that.
Be aware that I am not very experienced with react, so I don't know if this is the best way of doing this.
Cheers
=> Fix layout of edit mode when comment box is hidden

CHANGELOG.md, src/menu.js
Go learners can use analyzer as question & answer training. So switching analysis results shown/hidden is often to use.
I chose back quote (`) as the short key, that's can be discussed.
=> Added accelerator for board.show_analysis to show/hide analysis results handly.

package.json, webpack.config.js
This required an upgrade from Webpack 4 to Webpack 5 because Shudan 1.7.0 makes use of the nullish coalescing operator '??' which Webpack 4 fails to parse. Luckily, this was a pretty painless migration.
Closes #882.
=> Upgrade to Shudan 1.7.x

package.json
I don't understand why it was here in the first place, it gets
aliased to preact anyway. I've tested and diffed the final output
with/without in both dev and prod modes and can't find any
difference at all. So for the sake of clarity and shutting up
dependabot, I'm going to remove react from devDependencies
until I figure out why it was here in the first place.
@yishn if there's a good reason to keep it please let me know :)
I'm still pretty naive when it comes to the npm ecosystem.
=> Remove react from devDependencies

package.json, src/components/MarkdownContentDisplay.js
The API change in react-markdown 6.0.0 was a little deeper than I though, the renderers need to be converted to "components" according to their HTML entity types rather than their abstract markdown names.
Fixes #898.
=> Fix react-markdown component names

package.json, src/components/drawers/PreferencesDrawer.js, src/modules/helper.js
There's some sort of issue with recursive-copy's interaction with Electron's ASAR-patched fs module. This sidesteps the entire issue by just reimplementing the ASAR copy-extraction using native `fs` instead of involving third-party libraries.
This is now sync instead of async but I don't think this will matter.
Fixes #897.
=> Perform theme copy natively without recursive-copy

src/menu.js, src/modules/sabaki.js
For your consideration, here is an implementation of [Issue 773](https://github.com/SabakiHQ/Sabaki/issues/773).
Starting from the present node, this finds downstream forks and cycles through the possible variations by altering the `gameCurrents` array.  For myself, I prefer to have these new function calls bound to `Left` and `Right`, but in the interest of not surprising anyone, I bound these to `Shift+Left` and `Shift+Right`.
The function name is a bit jarring.  It doesn't act like a `goTo...`, so I didn't name it as such.
=> Issue 773 - cycle through downstream variations
