modules/gametree.js, modules/setting.js, style/index.css, view/index.html, view/index.js, view/index.view.js
=> New slider

README.md, modules/board.js, modules/gametree.js, modules/helper.js, modules/sgf.js, package.json, view/index.js, view/index.view.js
Rid Sabaki of the `tuple-w` node module.
=> Tuple free

CHANGELOG.md, style/goban.css, view/index.js, view/index.view.js
=> Scalable board markup

CHANGELOG.md, modules/board.js, modules/gametree.js, modules/gtp/index.js, modules/helper.js, style/index.css, test/boardTests.js, view/index.html, view/index.js, view/index.view.js
=> Non-square boards

CHANGELOG.md, main.js, modules/setting.js, style/app.css, style/goban.css, style/index.css, view/index.html, view/index.js, view/index.view.js
=> Animated fuzzy placement of stones

style/app.css, style/index.css, view/index.html, view/index.js, view/index.view.js
=> More tools for game collections

CHANGELOG.md, menu.json, modules/board.js, style/goban.css, style/index.css, view/index.html, view/index.ipc.js, view/index.js, view/index.view.js
=> Score Estimator

main.js, modules/board.js, modules/boardmatcher.js, modules/fuzzyfinder.js, modules/gametree.js, modules/gtp/index.js, modules/helper.js, modules/setting.js, modules/sgf.js, modules/sound.js, test/sgfTests.js, view/index.js, view/index.view.js
This is an attempt to convert the existing code to ES6, using the elegant syntax and language features of ES6. There will obviously be a problem with the web version of Sabaki, since browsers don't support ES6 yet. That will be subject to another PR.
Todo:
Testing:
=> Convert to ES6

browser/index.html, browser/index.js, browser/view.js, modules/menu.js, package.json
WIP PR to implement the features suggested in issue #160.
The code in its current state works perfectly with Ctrl+C and Ctrl+V and with the "Save to Clipboard" menu option. I am not sure if it is possible to implement the "Load from Clipboard" feature in a functional manner, so it may be necessary to add a text popup, which the user can manually copy. Or perhaps the copy/paste shortcuts would be enough with a instructions in the UI on how to use them.
=> web version clipboard loading and saving

browser/index.js, browser/view.js
Implements the request in issue #172.
=> Pop up comment menu by right clicking on last-played stone

components/drawers/InfoDrawer.js
=> [Fix #202] Fix typo in InfoDrawer.js

components/drawers/PreferencesDrawer.js
=> 'sabakitheme.asar' -> 'asar'

components/App.js
=> Fix move / position annotations not being stored as lists

components/App.js
=> Fix Clear Annotations

CHANGELOG.md, components/bars/AutoplayBar.js, modules/setting.js
Fixes https://github.com/yishn/Sabaki/issues/274
=> Allow up to 99s per move in Autoplay, step by 1s

docs/guides/theme-directory.md
Because, let's be honest, that's how everyone picks themes anyway :)
=> Add screenshots to theme directory

docs/guides/engines.md
Update for issue https://github.com/yishn/Sabaki/issues/296
Closes #296
=> [#296] Update guides - add Ray engine

docs/guides/theme-directory.md
=> added Dark theme

src/modules/board.js, src/modules/fileformats/gib.js, src/modules/fileformats/ngf.js
=> Use Q4 as 3rd handicap stone normally

docs/guides/theme-directory.md
Here is a pull request to add my Walnut and Wgo.js themes to the theme directory.
=> Add my Walnut and Wgo.js themes to the theme directory.

src/components/App.js, src/components/ContentDisplay.js, src/components/Goban.js, src/components/InputBox.js, src/components/MainView.js, src/modules/gametree.js, style/index.css
=> Support GoKibitz-style variations

package.json, src/components/App.js, src/components/Goban.js, src/menu.js
When analysis is toggled on, use `genmove_analyze` command to get analysis while generating a move. Also manually playing on the board shows analysis for each move.
=> Genmove analysis

src/components/App.js, src/components/GameGraph.js, src/components/Sidebar.js, src/components/Slider.js, src/components/WinrateGraph.js, src/components/drawers/CleanMarkupDrawer.js, src/main.js, src/modules/gametree.js, src/setting.js, style/index.css
Uses analysis data to plot a winrate graph. Saves data in SGF as well.
=> Winrate Graph

src/modules/rotation.js
Not sure if you'll approve of all these changes.
I also switched to using `tree.listNodes()` rather than recursing through the tree, it seemed simpler.
=> General cleanup of rotation.js

src/components/App.js, src/menu.js, src/modules/rotation.js
Some comments:
* Perhaps this file shouldn't be called rotation any more, or some functions should be moved out of it.
* Currently it just updates B, W, AB, and AW. Should we do metadata like PB, BR etc?
Closes #538
=> Initial swap colors function

.gitignore, docs/guides/building-tests.md, package.json
=> add portable file package support

src/setting.js
=> Local settings folder for portable app

src/components/sidebars/CommentBox.js
=> Fix the comment display issue

src/components/Goban.js
=> Fix the variation replay issue

docs/guides/theme-directory.md
Thank you so much to @upsided for his awesome work :)
=> Add upsided themes to theme directory
